### ISSUE TITLE
cudnnEngine.cpp - cuda error in execute :: 77 

### ISSUE THREAD

**Issue by zfc929** [chenzhi1992/TensorRT-SSD#18]
I run cade, error :

.........
flatten enqueue :1;121296
flatten enqueue :1;45486
flatten enqueue :1;12600
flatten enqueue :1;3150
flatten enqueue :1;756
latten enqueue :1;84
latten enqueue :1;733488
cudnnEngine.cpp - cuda error in execute :: 77

I does not how to do ?

**Comment by YaoLing13** [comment]
@zfc929 Hello, I met the same problem, Do you solve this problem?
