### ISSUE TITLE
SSD MobileNet .prototxt

### ISSUE THREAD

**Issue by Optimus1072** [chenzhi1992/TensorRT-SSD#27]
Hi will it be possible for you to share your mobileNet SSD prototxt?. I am able to run SSD -TensorRT with VGG as base. But with MobileNet SSD(taken from https://github.com/chuanqi305), I am getting this error 
inference: NvPluginSSD.cu:587: virtual void nvinfer1::plugin::DetectionOutput::configure(const nvinfer1::Dims*, int, const nvinfer1::Dims*, int, int): Assertion `numPriors*numLocClasses*4 == inputDims[0].d[0]' failed.
Aborted (core dumped)

Any help will be appreciated .
Thanks :-)

**Comment by chenzhi1992** [comment]
Ok， I will share mobilenet ssd prototxt.

**Comment by Ghustwb** [comment]
@Optimus1072 
Did you solve this problem? I have the same error Assertion 'numPriors*numLocClasses*4 == inputDims[param.inputOrder[0]].d[0]' failed.
I've already ran TensorRT-SSD successfully and now trying to run Mobilenet-SSD with TensorRT3.
Thank you.
