### ISSUE TITLE
ConcatLayer的实现

### ISSUE THREAD

**Issue by Orangels** [chenzhi1992/TensorRT-SSD#4]
您好,ConcatPlugin::enqueue() 这个方法中 ConcatLayer 可以开放下代码么?

**Comment by chenzhi1992** [comment]
@Orangels ok

**Comment by Orangels** [comment]
谢谢, 我自己读 caffe 的代码实现了cpu 计算的代码,关于 cuda 的代码还有些吃力,非常感谢

**Comment by chenzhi1992** [comment]
慢慢来


发自网易邮箱大师
在2018年01月29日 09:24，Orangels 写道:

谢谢, 我自己读 caffe 的代码实现了cpu 计算的代码,关于 cuda 的代码还有些吃力,非常感谢
